# Generated by Django 2.2.4 on 2019-08-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPFFR1', models.TextField()),
                ('TAS2R19', models.TextField()),
                ('ADRA2C', models.TextField()),
                ('SOWAHA', models.TextField()),
                ('TAS2R60', models.TextField()),
                ('KRT20', models.TextField()),
                ('AADACL4', models.TextField()),
                ('NACA2', models.TextField()),
                ('CLDN8', models.TextField()),
                ('GJC3', models.TextField()),
                ('FEM1A', models.TextField()),
                ('DRD5', models.TextField()),
                ('PABPC3', models.TextField()),
                ('HIST1H4C', models.TextField()),
                ('MC2R', models.TextField()),
            ],
        ),
    ]
