# Generated by Django 2.2.4 on 2019-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_visualise'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualise',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
